name: Terraform CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    TERRAFORM_VER: 1.14.0
    TERRAFORM_DIR: "terraform/"
    CLOUDSDK_VER: 512.0.0

jobs:
    tf-plan:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
            pull-requests: write

        steps:
            # Checkout the repository code
            - name: Code checkout
              id: code_checkout
              uses: actions/checkout@v4

            # Scan the repo for any sensitive information like secrets etc
            - name: Secret Scanning
              uses: trufflesecurity/trufflehog@main
              with:
                  path: ./ # Code repository path
                  base: "" # Start scanning from here
                  head: ${{ github.head_ref || github.ref_name }} # Scan commits until here
                  extra_args: --only-verified

            # Static code analysis using aqua security's tfsec
            - name: Run tfsec scan
              id: static_code_analysis
              uses: aquasecurity/tfsec-action@v1.0.3
              with:
                  working_directory: ${{ env.TERRAFORM_DIR }}
                  additional_args: --minimum-severity HIGH

            # Install the latest version of Google Cloud SDK
            - id: cloud_sdk_installation
              name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.3.0
              with:
                  version: ${{ env.CLOUDSDK_VER }}

            # Setup the authentication for the Google Cloud using WIF
            - id: gcp_auth
              name: Authenticate to GCP
              uses: google-github-actions/auth@v0.3.1
              with:
                  create_credentials_file: "true"
                  workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
                  service_account: ${{ secrets.SERVICE_ACCOUNT }}

            # Install the specified version of Terraform CLI
            - id: tf_installation
              name: Terraform Installation
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TERRAFORM_VER }}

            - name: init
              run: terraform init
              working-directory: ${{ env.TERRAFORM_DIR }}

            - name: plan
              run: terraform plan
              working-directory: ${{ env.TERRAFORM_DIR }}

    tf-apply:
        needs: tf-plan
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TERRAFORM_VER }}
            - name: Init
              run: terraform init
              working-directory: ${{ env.TERRAFORM_DIR }}
            - name: Apply
              run: terraform apply -auto-approve
              working-directory: ${{ env.TERRAFORM_DIR }}
